# Generated by Django 5.1.6 on 2025-03-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('est_inscrit', models.BooleanField()),
                ('metiers', models.CharField(choices=[('APD', 'APD'), ('DBE', 'DBE'), ('ABD', 'ABD')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
